# Academic and Social Services

conference_journal_reviewer:
  # leadership_roles:
  #   - role: "Area Chair"
  #     venues: ["NeurIPS", "ACL Rolling", "CCL"]
  #   - role: "Session Chair and Meta-Reviewer"
  #     venues: ["IJCAI"]
  #   - role: "Young Editorial Board Member"
  #     venues: ["JAICS", "BDIA"]
  
  # workshop_chairs:
  #   - role: "SIGIR 2025 Workshop Program Chair"
  #     year: "2025"
  #   - role: "IEEE ICBDSE 2025 Workshop Chair"
  #     year: "2025"
  #   - role: "IEEE DLCV 2025 Workshop Chair"
  #     year: "2025"
  
  conference_reviews:
    venues: ["NeurIPS", "ICML", "ICLR", "KDD", "AAAI", "IJCAI", "SIGIR", "ACM MM", "ACL", "EMNLP", "CIKM", "WSDM", "ICDM", "DASFFA"]
  
  journal_reviews:
    venues: ["Cell Patterns", "IEEE TIP", "Pattern Recognition", "Neurocomputing", "International Journal of Machine Learning and Cybernetics"] 
